import json
import re
from datetime import datetime, timezone
from pathlib import Path

TEMPLATES_ROOT = Path.home() / ".gridreport" / "templates"

BRAND_NAME_RE = re.compile(r"[a-zA-Z0-9_-]+")

THEME_CSS_TEMPLATE = """/* {brand} — generated by gridreport learn on {learned_at} from {source_url} */
:root {{
  --primary: {primary};
  --secondary: {secondary};
  --accent: {accent};
  --text: #262626;
  --muted: #6b7280;
  --border: #dcdfe3;
  --code-bg: #f4f5f7;
}}

@page {{
  size: A4;
  margin: 3cm 2cm 2.4cm 2cm;
  @top-center {{ content: element(pageHeader); }}
  @bottom-center {{
    content: "Page " counter(page) " of " counter(pages);
    font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
    font-size: 8.5pt;
    color: var(--muted);
  }}
}}

#page-header {{
  position: running(pageHeader);
  border-bottom: 1.5pt solid var(--accent);
  padding-bottom: 6pt;
  width: 100%;
  overflow: hidden;
}}
#page-header img {{ height: 20pt; float: left; }}
#page-header .doc-title {{
  float: right;
  max-width: 70%;
  line-height: 20pt;
  font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
  font-size: 9pt;
  color: var(--primary);
  font-weight: 600;
  text-align: right;
}}

body {{
  font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
  font-size: 10.5pt;
  line-height: 1.55;
  color: var(--text);
}}

h1, h2, h3, h4 {{ page-break-after: avoid; break-after: avoid; }}
h1 {{
  color: var(--primary);
  font-size: 21pt;
  border-bottom: 2.5pt solid var(--accent);
  padding-bottom: 6pt;
  margin-top: 0;
}}
h2 {{
  color: var(--primary);
  font-size: 14.5pt;
  margin-top: 22pt;
  border-bottom: 0.75pt solid var(--border);
  padding-bottom: 3pt;
}}
h3 {{ color: var(--secondary); font-size: 12pt; margin-top: 16pt; }}
h4 {{ color: var(--primary); font-size: 10.5pt; margin-top: 12pt; }}

p {{ orphans: 3; widows: 3; }}
a {{ color: var(--secondary); text-decoration: none; }}

table {{
  width: 100%;
  table-layout: auto;
  border-collapse: collapse;
  margin: 12pt 0;
  font-size: 9.5pt;
}}
thead {{ display: table-header-group; }}
tr {{ page-break-inside: avoid; break-inside: avoid; }}
th {{
  background: var(--primary);
  color: #ffffff;
  text-align: left;
  padding: 6pt 8pt;
  font-weight: 600;
  overflow-wrap: break-word;
}}
td {{ padding: 5pt 8pt; border-bottom: 0.5pt solid var(--border); vertical-align: top; overflow-wrap: break-word; }}
td code, th code {{ overflow-wrap: anywhere; word-break: break-all; }}
tr:nth-child(even) td {{ background: #fafafa; }}

code {{
  font-family: "SF Mono", "Consolas", "Menlo", monospace;
  font-size: 9pt;
  background: var(--code-bg);
  padding: 1.5pt 4pt;
  border-radius: 3pt;
}}
pre {{
  background: var(--code-bg);
  border-left: 3pt solid var(--accent);
  padding: 8pt 10pt;
  font-size: 8.5pt;
  line-height: 1.4;
  overflow-wrap: break-word;
  white-space: pre-wrap;
  page-break-inside: avoid;
  break-inside: avoid;
  border-radius: 0 4pt 4pt 0;
}}
pre code {{ background: none; padding: 0; }}

blockquote {{
  border-left: 3pt solid var(--accent);
  margin: 10pt 0;
  padding: 4pt 12pt;
  color: var(--muted);
  font-style: italic;
}}

hr {{ border: none; border-top: 0.75pt solid var(--border); margin: 18pt 0; }}
ul, ol {{ margin: 6pt 0; padding-left: 20pt; }}
li {{ margin: 3pt 0; }}
strong {{ color: var(--primary); }}
"""


def sanitize_brand_name(name: str) -> str:
    if not BRAND_NAME_RE.fullmatch(name):
        raise ValueError(
            f"invalid brand name {name!r}: only letters, numbers, hyphens, and underscores are allowed"
        )
    return name


def write_template(
    template_dir: Path,
    brand: str,
    source_url: str,
    colors: dict,
    logo_src: Path | None,
) -> None:
    template_dir.mkdir(parents=True, exist_ok=True)
    learned_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    logo_filename = None
    if logo_src is not None:
        logo_filename = f"logo{logo_src.suffix}"
        (template_dir / logo_filename).write_bytes(logo_src.read_bytes())

    css = THEME_CSS_TEMPLATE.format(brand=brand, learned_at=learned_at, source_url=source_url, **colors)
    (template_dir / "theme.css").write_text(css, encoding="utf-8")

    meta = {
        "brand": brand,
        "source_url": source_url,
        "learned_at": learned_at,
        "colors": colors,
        "logo_file": logo_filename,
    }
    (template_dir / "meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
